source 'https://github.com/CocoaPods/Specs.git'
source 'http://git.bogokj.com/fandong/BogoSpec.git'

#use_frameworks!

platform :ios, '9.0'

target 'FDNetworkObjC_Example' do
  pod 'FDNetworkObjC', :path => '../'

  target 'FDNetworkObjC_Tests' do
    inherit! :search_paths

    
  end
end
